# -*- coding: utf-8 -*-
"""Q4 Calling File

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PC3WOzQwzkhV8J8-r5PaPjBLdIAK58FL
"""

import numpy as np
from junctionTreeAlgo import junction_tree

#here pot is initialized with potentials of the test case but can be replaced by any other cliques potentials
pot = np.array([[[0.1,0.7],[0.8,0.3]],[[0.5,0.1],[0.1,0.5]],[[0.1,0.5],[0.5,0.1]],[[0.9,0.3],[0.1,0.3]]])
junction_tree(pot)